net_services: "10.10.10.1"
virtualization_servers:
- name: "PVE"
  ip_address: "10.10.10.10"
  username: "ansible"
  ssk_key:"PVE_id_rsa"
clusters:
- name: "K8s01"
  state: present  #present, absent, recreate
  cluster_ip: "10.162.253.202"
  controlplanes:
  - name: "K8s01cp01"
    vm_id: "1010"
    cpu: "2"
    core: "2"
    memory: "4Gb"
    storage: "32Gb"
    state: "present"
  - name: "K8s01cp02"
    vm_id: "1011"
    cpu: "2"
    core: "2"
    memory: "4Gb"
    storage: "32Gb"
    state: "present"
  - name: "K8s01cp03"
    vm_id: "1012"
    cpu: "2"
    core: "2"
    memory: "4Gb"
    storage: "32Gb"
    state: "present"
  workers:
  - name: "K8s01w01"
    vm_id: "1015"
    cpu: "4"
    core: "4"
    memory: "8Gb"
    storage: "32Gb"
    state: "present"
  - name: "K8s01w02"
    vm_id: "1016"
    cpu: "4"
    core: "4"
    memory: "8Gb"
    storage: "32Gb"
    state: "stopped"