net_services: "10.162.253.1"
virtualization_servers:
- name: "PVE"
  ip_address: "pve.devops.sgmdev.hu"
  username: "root"
  private_key_path: "./PVE_id_rsa"
clusters:
- name: "K8s05"
  state: present  #present, absent, recreate, stop
  cluster_ip: "10.162.253.202"
  controlplanes:
  - name: "VM-K8s05cp01"
    vm_id: "2010"
    cpu: "2"
    core: "2"
    memory: "4096"
    storage: "32G"
    state: "present"
    server: "PVE"
  - name: "VM-K8s05cp02"
    vm_id: "2011"
    cpu: "2"
    core: "2"
    memory: "4096"
    storage: "32G"
    state: "present"
    server: "PVE"
  - name: "VM-K8s05cp03"
    vm_id: "2012"
    cpu: "2"
    core: "2"
    memory: "4096"
    storage: "32G"
    state: "present"
    server: "PVE"
  workers:
  - name: "VM-K8s05w01"
    vm_id: "2015"
    cpu: "4"
    core: "4"
    memory: "8192"
    storage: "32G"
    state: "present"
    server: "PVE"
  - name: "VM-K8s05w02"
    vm_id: "2016"
    cpu: "4"
    core: "4"
    memory: "8192"
    storage: "32G"
    state: "stopped"
    server: "PVE"
